@startuml
|运维工程师|
start
:创建维保工单;
|维保工程师|
(A)
:签收工单;
:判断故障解决方式;
if(故障是否可以修复？)then(可以修复)
    split
    :现场修复;
    split again
    :返厂修理;
    end split
    :解决故障;
    :提交审核申请;
else(无法修复)
    :请求技术支持;
    |市场部专责|
    repeat
        :评估故障情况;
        if(是否发起部门协作)then(不发起)
            :退回工单;
            (A)
            kill
        else(发起)
            |平台工程师/创新中心专责|
            if(故障是否可以修复)then(可以修复)
                :填写消缺表单;
            else(无法修复)
                :填写处理意见;
            endif
            :返回处理结果;
            |市场部专责|
            :汇总处理结果;
        endif
    repeat while(是否还存在故障？)is(存在)not(不存在)
endif
|运维工程师|
if(审核是否通过？)then(不通过)
    |运维工程师|
    :再次处理;
    (A)
    kill
else(通过)
    :填写验收评价;
    |市场部专责|
    :填写服务评价;
    :确认结单\n流程结束;
    end
@enduml


