@startuml
|网格管理员|
fork
    :建立运维策略;
    :依据策略建立计划;
fork again
    :建立临时计划;
fork again
    |场站管理员|
    :建立计划;
fork again
    |运维工程师|
    :建立计划;
end fork
|运维工程师|


'split
'    -[hidden]->
'    :建立运维策略;
'    :依据策略建立计划;
'split again
'    -[hidden]->
'    :建立临时计划;
'split again
'    -[hidden]->
'    |场站管理员|
'    :建立计划;
'split again
'    -[hidden]->
'    |运维工程师|
'    :建立计划;
'end split

:系统根据计划自动生成运维工单;
repeat
    :签收工单;
    :按相应流程完成工单;
    :提交审核申请;
    |场站管理员|
repeat while(审核是否通过？)is(不通过)not(通过)
:确认结单\n流程结束;
end
@enduml


